name: Day_2 CI

on:
  push:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'Day_2/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64
      
      - name: Build with MSBuild
        run: msbuild AdventofCode.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=x64 /v:minimal
      
      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.configuration }}
          path: bin/
