name: Day_3 CI

on:
  push:
    branches: [ '*' ]
    paths:
    - 'Day_3/**'
  pull_request:
    branches: [ '*' ]
    paths:
    - 'Day_3/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build with MSBuild
      run: msbuild Day_3/Day_3.vcxproj /p:Configuration=Release
